bitnami/vulndb

- README.md
- config/components/wavefront.json
> [bitnami/wavefront] Deprecate wavefront

- config/components/jasperreports-pro.json
Remove information of this component
- fixes #
> Deprecate JasperReports Pro

- README.md
- config/components/wavefront-proxy.json
> [bitnami/wavefront-proxy] Deprecate Wavefront Proxy

- README.md
- config/components/wavefront-prometheus-storage-adapter.json
Deprecate Wavefront Prometheus Adapter.
> [bitnami/wavefront-prometheus-storage-adapter] Deprecate Wavefront Prometheus Adapter

- .github/workflows/ci-pipeline.yml
- config/components/acmesolver.json
Fix error getting number of modified files.
Manually review logic works as expected.
None.
> Fix typo in CI pipeline

- config/components/deepspeed.json
> [bitnami/deepspeed] chore: :wrench: Add to vulndb

- README.md
- config/components/harbor-notary-server.json
- config/components/harbor-notary-signer.json
Deprecate Harbor Notary Signer and Harbor Notary Server
> [bitnami/harbor-notary-*] Deprecate Harbor Notary Signer and Harbor Notary Server

- config/components/mlflow.json
This PR adds the vulndb definition for mlflow. Used this CVE as a base
https://nvd.nist.gov/vuln/detail/CVE-2023-2356
- fixes #
> [bitnami/mlflow] chore: :wrench: Add to vulndb

- config/components/natscli.json
- config/components/pinniped-cli.json
> [bitnami/natscli,pinniped-cli] chore: :wrench: Add to vulndb

- config/components/tensorflow.json
> [bitnami/tensorflow] chore: :wrench: Add to vulndb

- config/components/neo4j.json
Update `neo4j` configuration
Properly track neo4j CVEs.
Not expected.
> [bitnami/neo4j] Update config

- config/components/drush.json
Update drush configuration.
Properly track drush CVEs.
Not expected
> [bitnami/drush] Update config

- config/components/mysql-client.json
Update mysql-client configuration.
Properly track mysql-client CVEs.
Not expected.
> [bitnami/mysql-client] Update config

- README.md
- config/components/mxnet.json
Deprecate mxnet. See [upstream](https://mxnet.apache.org/versions/1.9.1/)
> [bitnami/mxnet] Deprecate mxnet

- README.md
- config/components/processmaker.json
> [bitnami/processmaker] Deprecate ProcessMaker

- README.md
- config/components/tinytinyrss.json
- config/components/ttrss-mailer-smtp.json
Deprecate Tinytinyrss along with ttrss-mailer-smtp.
> [bitnami/tinytinyrss] Deprecate tinytinyrss

- README.md
- config/components/canvas-rce-api.json
- config/components/canvaslms.json
Deprecate Canvas LMS along with Canvas RCE API.
> [bitnami/canvaslms] Deprecate canvaslms

- README.md
- config/components/concrete5.json
> [bitnami/concrete5] Deprecate concrete5

- README.md
- config/components/weblate.json
> [bitnami/weblate] Deprecate weblate

- README.md
- config/components/neos.json
> [bitnami/neos] Deprecate neos

- README.md
- config/components/reportserver.json
> [bitnami/reportserver] Deprecate reportserver

- README.md
- config/components/orocrm.json
> [bitnami/orocrm] Deprecate orocrm

- README.md
- config/components/roundcube.json
> [bitnami/roundcube] Deprecate roundcube

- README.md
- config/components/mantis.json
> [bitnami/mantis] Deprecate mantis

- README.md
- config/components/mybb.json
> [bitnami/mybb] Deprecate mybb

- README.md
- config/components/abantecart.json
> [bitnami/abantencart] Deprecate abantecart

- README.md
- config/components/phplist.json
> [bitnami/phplist] Deprecate phplist

- README.md
- config/components/seopanel.json
> [bitnami/seopanel] Deprecate seopanel

- README.md
- config/components/civicrm.json
> [bitnami/civicrm] Deprecate CiviCRM

- README.md
- config/components/osclass.json
> [bitnami/osclass] Deprecate Osclass

- README.md
- config/components/codeigniter.json
- config/components/symfony.json
Those assets are being deprecated
> Deprecate codeigniter and symfony

- README.md
- config/components/typo3.json
> Deprecate Typo3

- README.md
- config/components/jasperreports.json
> [bitnami/jasperreports] Deprecate jasperreports

- README.md
- config/components/kapacitor.json
- config/components/percona-xtrabackup-binary.json
- config/components/percona-xtrabackup.json
Those assets are being deprecated
> [bitnami/kapacitor bitnami/percona-xtrabackup] Add deprecation for those assets

- README.md
- config/components/modx.json
> [bitnami/modx] Deprecate modx

- README.md
- config/components/jruby.json
> [bitnami/jruby] deprecate jruby

- config/components/liferay.json
Mark liferay to be deprecated as no longer supported.
> [bitnami/liferay] Deprecate liferay

- config/components/miniconda.json
Update CPE string for miniconda.
https://nvd.nist.gov/vuln/detail/CVE-2022-26526
CVEs are properly tracked.
Not expected.
> [bitnami/miniconda] Update CPE information

- config/components/seaweedfs.json
VulnDB config for new container.
> [bitnami/seaweedfs] Add config

- config/components/cypress.json
> [bitnami/cypress] chore: :wrench: Add to vulndb

- config/components/janusgraph.json
> [bitnami/janusgraph] Add to vulndb

- config/components/scylladb.json
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>
This PR adds scylladb to the vulnerability database. Looking at a sample CVE https://nvd.nist.gov/vuln/detail/CVE-2023-33972, vendor and application would be `scylladb`.
- fixes #
> [bitnami/scylladb] chore: :wrench: Add to vulndb

- README.md
- config/components/kafka-exporter.json
Deprecate Kafka Exporter
- fixes #
Solution has not been updated since May 2023
> [bitnami/kafka-exporter] Deprecate kafka-exporter

- README.md
Fix linter errors in the README file
- fixes https://github.com/bitnami/vulndb/actions/runs/9210868599/job/25338869449
> Fix linter errors in the README

- README.md
- config/components/simplemachinesforum.json
Mark Simple Machines Forum as a deprecated asset.
> [bitnami/simplemachinesforum] Deprecate Simple Machines Forum

- README.md
- config/components/alfresco-pdf-renderer.json
- config/components/alfresco-search-services.json
- config/components/alfresco-transform-core.json
- config/components/alfresco.json
> [bitnami/alfresco] Deprecate alfresco

- README.md
- config/components/openfire.json
> [bitnami/openfire] Deprecate openfire

- README.md
- config/components/silverstripe.json
> [bitnami/silverstripe] chore: :wrench: :wastebasket: Add deprecation date

- config/components/nessie-utils.json
- config/components/nessie.json
> [bitnami/nessie] chore: :wrench: Add to vulndb

- config/components/dremio.json
> [bitnami/dremio] chore: :wrench: Add to vulndb

- valkey.json
> [bitnami/valkey] Add to vulndb

- README.md
- config/components/akeneo.json
> [TAC-1036] Deprecate akeneo

- README.md
- config/components/activemq.json
> [bitnami/activemq] Deprecate ActiveMQ

- README.md
- config/components/espocrm.json
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>
- fixes #
> [bitnami/espocrm] chore: :wrench: :wastebasket: Add deprecation date

- README.md
- config/components/resourcespace.json
Marks the application to be deprecated
> [bitnami/resourcespace] Deprecate ResourceSpace

- README.md
- config/components/guacamole-auth-jdbc-extension.json
- config/components/guacamole-server.json
- config/components/guacamole.json
Marks the application to be deprecated
> [TAC-1040] Deprecate Guacamole

- config/components/hyperledger-fabric-ca.json
- config/components/hyperledger-fabric-orderer.json
- config/components/hyperledger-fabric-peer.json
- config/components/hyperledger-fabric-tools.json
Signed-off-by: Javier Salmeron Garcia <jsalmeron@vmware.com>
This PR adds to vulndb hyperledger-fabric (in the peer, orderer and tools containers) and hyperledger-fabric-ca
> [bitnami/hyperledger-fabric] chore: :wrench: Add to vulndb

- config/components/charts-syncer.json
This PR adds [charts-syncer](https://github.com/bitnami/charts-syncer) to the vulnerability database.
None
None
N/A
> chore: Add chart-syncer to vulndb

- config/components/phpbb.json
Add 'to-be-deprecated' to phpbb component.
Date 1 month from today (2024-09-06).
> [bitnami/phpbb] Add to-be-deprecated

- config/components/zipkin.json
This PR adds zipkin to vulndb. We did not find any entry in NVD, so we use the default values
- fixes #
> [bitnami/zipkin] chore: :wrench: Add to vulndb

- config/components/node-min.json
> [add/node-min] Add node-min

- config/components/php-min.json
> [add/php-min] Add php-min

- config/components/ruby-min.json
> [TNZ-25810] Add ruby-min

- config/components/java-min.json
- config/components/jre.json
> [bitnami/jre, java-min] chore: :wrench: Add to vulndb

- config/components/apache-serf.json
Adds CPE information for Apache Serf.
> [bitnami/apache-serf] Add Apache Serf

- config/components/superset.json
> [bitnami/superset] Add superset

- config/components/minio-operator-sidecar.json
- config/components/minio-operator.json
This PR adds the vulndb entries for minio-operator and minio-operator-sidecar
- fixes #
> [bitnami/minio-operator] chore: :wrench: Add to vulndb

- config/components/kes.json
This PR adds the vulndb files for kes
- fixes #
> [bitnami/kes] chore: :wrench: Add to vulndb

- README.md
Removes warning quote from README.md file. We consider the database is now stable, as no more major changes are expected, and some vulnerability scanners already ingest it.
> Remove alpha section from README.md

- config/components/clickhouse-keeper.json
- config/components/clickhouse-operator.json
This PR adds the basic configuration for two new components: ClickHouse Keeper & ClickHouse Operator.
> feat: Add ClickHouse Keeper & ClickHouse Operator

- config/components/clickhouse-operator-metrics-exporter.json
This PR adds the basic configuration for a new component: ClickHouse Operator Metrics exporter
> feat: Add ClickHouse Operator Metrics exporter

- config/components/kserve-agent.json
- config/components/kserve-localmodel-controller.json
- config/components/kserve-localmodelnode-agent.json
- config/components/kserve-router.json
- config/components/kserve-storage-initializer.json
- config/components/kserve.json
This PR adds the vulndb entries for the kserve containers. In all of them, the product is kserve
- fixes #
> [bitnami/kserve] chore: :wrench: Add to vulndb

- README.md
- config/components/vmod-querystring.json
https://vmw-jira.broadcom.net/browse/TNZ-34706
> Deprecate vmod-querystring

- config/validation/README.md
- config/validation/schema.json
Bump OSV schema version.
Support CVSS v4.
> feature(CVSSv4): Bump OSV schema version

- config/components/envoy-gateway.json
- config/components/envoy-ratelimit.json
This PR adds the vulndb entries for envoy-gateway and envoy-ratelimit
> [bitnami/envoy-gateway] chore: :wrench: Add to vulndb

- README.md
**Description of the change**
Logo URL updated
> [bitnami] Update Bitnami logo URL

- README.md
- config/components/kubeapps-apis.json
- config/components/kubeapps-apprepository-controller.json
- config/components/kubeapps-asset-syncer.json
- config/components/kubeapps-pinniped-proxy.json
- config/components/kubeapps.json
https://vmw-jira.broadcom.net/browse/TNZ-42107
> Deprecate Kubeapps

- config/components/grafana-k6-operator.json
- config/components/grafana-k6.json
- config/components/scuttle.json
This PR adds the vulndb entries for grafana-k6, grafana-k6-operator and scuttle
> [bitnami/grafana-k6] chore: :wrench: Add to vulndb

- config/components/grafana-alloy.json
> [TNZ-34041] Add grafana-alloy to vulndb

- README.md
- config/components/spring-cloud-dataflow-composed-task-runner.json
- config/components/spring-cloud-dataflow-shell.json
- config/components/spring-cloud-dataflow.json
- config/components/spring-cloud-skipper-shell.json
- config/components/spring-cloud-skipper.json
https://vmw-jira.broadcom.net/browse/TNZ-43479
> Deprecate Spring Cloud

- config/components/minio-object-browser.json
This PR adds [MinIO Console](https://github.com/minio/object-browser) to vulndb
> feat: Add MinIO Console to vulndb

- README.md
- config/components/promtail.json
This product is not maintained anymore by the upstream
> Deprecate Promtail

- config/components/grafana-pyroscope.json
This PR adds the basic files for grafana-pyroscope. Using grafana as the vendor
> [bitnami/grafana-pyroscope] chore: :wrench: Add to vulndb

- config/components/strimzi-kafka-operator.json
This PR adds Strimzi Kafka Operator to vulndb.
> [bitnami/strimzi-kafka-operator] chore: Add to vulndb

- config/components/strimzi-kafka-bridge.json
This PR adds Strimzi Kafka Bridge to vulndb.
> [bitnami/strimzi-kafka-bridge] chore: Add to vulndb
