.github/workflows/ci-pipeline.yml

With these changes, manual review will be required in case too many files are modified at the same time. Selected threshold is `20` files, as the current mean number of modified files isn't above the 10-15 range.
It is harder to merge a major change that may break vulnerability feed usage.
Manual review will be required in case we are in a rush for publishing any major update.

Manually review PR modifying too many files

---

README.md
config/components/bitnami-shell.json

This asset is deprecated in favor of [OS Shell](https://github.com/bitnami/containers/tree/main/bitnami/os-shell)

Deprecate bitnami-shell from vulndb

---

.github/workflows/ci-pipeline.yml
scripts/lint.sh

`json-schema` shows a deprecation warning in favour of `check-jsonschema`. This PR replaces one tool with the other.
```
root@99d04b456ae9:/vulndb# jsonschema "./config/validation/schema.json" < "./data/apache/BIT-2023-25690.json"; echo "exitCode: $?"
/opt/bitnami/python/bin/jsonschema:5: DeprecationWarning: The jsonschema CLI is deprecated and will be removed in a future version. Please use check-jsonschema instead, which can be installed from https://pypi.org/project/check-jsonschema/
from jsonschema.cli import main
exitCode: 0
```
Remove internal dependency on deprecated tools.
Not expected.
Local test:
```
root@b17617f7a6c9:/vulndb# check-jsonschema --schemafile ./config/validation/schema.json ./data/apache/BIT-2023-27522.json; echo "exitCode: $?"
ok -- validation done
exitCode: 0 …
```

Replace json-schema with check-jsonschema

---

config/components/nginx-ingress-controller.json

Update CPE information for NGINX Ingress Controller in order to point to the right product we ship.
Correct information is provided. No false positives.
None
NA
Our `bitnami/nginx-ingress-controller` [container](https://github.com/bitnami/containers/tree/main/bitnami/nginx-ingress-controller) is based on https://kubernetes.github.io/ingress-nginx/ and not on https://docs.nginx.com/nginx-ingress-controller/.
As it might be inferred, both are different products with different versioning (and hence, different CPE as well). You can check that using NVD for a vulnerability that affects K8s's NGINX-IC ([CVE-2022-4886](https://nvd.nist.gov/vuln/detail/CVE-2022-4886)) vs. one that affects F5's NGINX-IC (https://nvd.nist.gov/vuln/detail/CVE-2021-23055).

fix: CPE information for NGINX Ingress Controller

---

config/components/jenkins.json

[Jenkins](https://www.jenkins.io/download/) has 2 versions:
- LTS, also called stable
- Weekly
We only release the LTS version and as such our CPE should only refer to that version.
If a CVE is only present in the weekly version vulndb won't report a CVE our bitnami/jenkins release.
None
Jenkins' [CPE summary](https://nvd.nist.gov/products/cpe/detail/0F11B1A6-957A-45E5-8EEA-E10DC7B40C95)

Update Jenkins CPE to only capture LTS version

---

config/components/cilium-operator.json

Follows up https://github.com/bitnami/vulndb/pull/441 configuring Cilium Operator to use `cilium` as _cpeVendor_ & _cpeProduct_.

[cilium-operator]: Configure cpeVendor & cpeProduct

---

config/components/grpc-health-probe.json
config/components/hubble-relay.json

This PR adds Hubble Relay (part of [Cilium](https://cilium.io/)) and [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) to the vulnerability database.
Vendor and application would be `cilium` for Hubble Relay given it's a sub-component of Cilium.
There's no information about CVE for grpc-health-probe on National Vulnerability Database.
None
None
N/A

chore: Add Hubble Relay & related components to vulndb

---

config/components/publify.json
config/components/redash.json

This PR updates Publify & Redash configuration to mark them as "to-be-deprecated".
N/A
None
None
N/A

chore: Deprecate Publify & Redash

---

config/components/hubble-ui-backend.json
config/components/hubble-ui.json

This PR adds Hubble UI (part of [Cilium](https://cilium.io/)) components to the vulnerability database.
Vendor and application would be `cilium` for Hubble UI & Hubble UI Backend given they're sub-components of Cilium.
None
None
N/A

chore: Add Hubble UI components to vulndb

---

config/components/cilium-proxy.json

This PR adds Cilium Proxy (part of [Cilium](https://cilium.io/)) to the vulnerability database.
Vendor and application would be `cilium` for Cilium Proxy given it's a sub-component of Cilium.
None
None
N/A

chore: Add Cilium Proxy to vulndb

---

config/components/bpftool.json
config/components/llvm.json

This PR adds new Cilium sub-components (LLVM & bpftool) to the vulnerability database.
None
None
N/A

chore: Add new Cilium sub-components to vulndb

---

config/components/miniconda.json
config/components/miniforge.json

This pull request adds the miniforge component to the vundb database. Miniforge is a minimal installer for Conda specific to conda-forge, which will enhance the functionality of our vundb database.
- Improves the package management capabilities of the vundb database
- Did not find a CVE entry for miniforge, so we’re inferring the same as miniconda
- fixes #1663
The integration of miniforge into vundb has been tested locally and appears to work as expected. However, extensive testing in various environments is recommended before merging.

[bitnami/miniforge] chore: :wrench: :wastebasket: Add to vulndb and deprecate miniconda

---

README.md
config/components/supabase-pljava.json
config/components/supabase-postgres-meta.json
config/components/supabase-postgres.json
config/components/supabase-realtime.json
config/components/supabase-storage.json
config/components/supabase-vault.json
config/components/supabase-wrappers.json
config/components/supabase.json

As part of our internal catalog review process, we've decided to drop support for Supabase. 
This implies that we'll mark the product as deprecated and it will not receive new updates.
This PR marks Supabase components as deprecated.

[bitnami/supabase-*] Deprecate Supabase components

---

config/components/groonga.json
config/components/hypopg.json
config/components/pg-safeupdate.json
config/components/pg_cron.json
config/components/pg_hashids.json
config/components/pg_jsonschema.json
config/components/pg_net.json
config/components/pg_plan_filter.json
config/components/pg_repack.json
config/components/pg_stat_monitor.json
config/components/pgjwt.json
config/components/pgroonga.json
config/components/pgrouting.json
config/components/pgsodium.json
config/components/pgsql-http.json
config/components/pgtap.json
config/components/pgvector.json
config/components/plpgsql_check.json
config/components/plv8.json
config/components/timescaledb.json

Follows up https://github.com/bitnami/vulndb/pull/584 marking as deprecated every library that was exclusively used to compile Supabase Postgres.

[bitnami/supabase-*] Deprecate Supabase Postgres libraries

---

.github/workflows/ci-pipeline.yml

This PR fixes `check-jsonschema` installation currently failing with the error below:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
note: If you believe …
```

ci: fix check-jsonschema installation

---

config/components/alertmanager.json

Adds the correct cpe vendor for Alertmanager.  NVD has vendor as `prometheus`.
Correct tracking of alertmanager vulnerabilities.
None noted
- fixes #658
I do not know how the spdx file inside the container is generated.  If not via this config file, that should get changed as well as it curently shows `cpe:2.3:*:alertmanager:alertmanager:0.27.0:*:*:*:*:*:*:*`.
I assume the process to generate vulnerability records is not public, so unsure how actual alertmanager records will get added here.

Fix alertmanager component

---

README.md
config/components/airflow-exporter.json
config/components/airflow-scheduler.json
config/components/airflow-worker.json

As part of our internal catalog review process, we've decided to remove these Airflow sub-components from the catalog given they're no longer used on the Airflow chart nor the SingleVM.
This PR marks Airflow Exporter, Scheduler & Worker components as deprecated.

[bitnami/airflow-*] Deprecate Airflow sub-components

---

.github/workflows/cd-pipeline.yml
.github/workflows/ci-pipeline.yml
.github/workflows/pr-reviews.yml

Pinning an action to a full length commit SHA is currently the only way to use a non-immutable action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload
Clears security concerns related to GitHub Actions.
Not expected.
* https://github.com/bitnami/vulndb/security/code-scanning/6
* https://github.com/bitnami/vulndb/security/code-scanning/7
* https://github.com/bitnami/vulndb/security/code-scanning/8
* https://github.com/bitnami/vulndb/security/code-scanning/9

[actions] Pin GitHub actions with commit hashes

---

.github/workflows/cd-pipeline.yml

This PR adds GChat notifications to the CD pipeline.
When the pipeline fails, it will notify the team with a message using the gchat-notification worflow from bitnami/support
None known.

github-actions: Add gchat notification

---

.github/workflows/cd-pipeline.yml

Check repository ownership to avoid running scheduled or CD workflows in forked repositories.
Skip unnecessary executions and failures in forks.
None

[bitnami/vulndb] chore(workflows): Avoid running scheduled workflows in forked repositories

---

config/components/cadvisor.json

This PR adds the definition of cadvisor. Using the GH Repo as the reference, we assume that the vendor is Google.

[bitnami/cadvisor] chore: :wrench: Add to vulndb

---

README.md

We are working on adding more information to our CVEs. In this case, we are adding the `summary` field to our records from the information available at the https://github.com/CVEProject/cvelistV5 repository.

[bitnami/vulndb] Reference cvelistV5 in README.md

---

config/components/influxdb-core.json

This PR adds the configuration for `influxdb-core`, an alias for `influxdb`.

chore: influxdb-core as alias for influxdb

---

README.md
config/components/kaniko.json

We'll restore the deprecated Kaniko using a new [maintained fork](https://github.com/chainguard-dev/kaniko).
Partially revert https://github.com/bitnami/vulndb/pull/962

Restore kaniko support

---

README.md
config/components/dolibarr.json

This PR marks Dolibarr to be deprecated in a month (August 31st).

chore: deprecate Dolibarr
